!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  auto_exposure: true
  auto_gain: true
  auto_shutter: false
  auto_white_balance: false
  brightness: 0.0
  enable_strobe1: false
  enable_trigger: false
  enable_trigger_delay: false
  exposure: 0.0
  format7_color_coding: raw8
  format7_roi_height: 0
  format7_roi_width: 0
  format7_x_offset: 0
  format7_y_offset: 0
  frame_rate: 9.214188575744629
  gain: 0.0
  gamma: 0.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      auto_exposure: true
      auto_gain: true
      auto_shutter: false
      auto_white_balance: false
      brightness: 0.0
      enable_strobe1: false
      enable_trigger: false
      enable_trigger_delay: false
      exposure: 0.0
      format7_color_coding: raw8
      format7_roi_height: 0
      format7_roi_width: 0
      format7_x_offset: 0
      format7_y_offset: 0
      frame_rate: 9.214188575744629
      gain: 0.0
      gamma: 0.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      pan: 56
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      shutter_speed: 0.009995878219604492
      state: true
      strobe1_delay: 0.0
      strobe1_duration: 1.0
      strobe1_polarity: 1
      tilt: 0
      trigger_delay: 0.0
      trigger_mode: mode0
      trigger_parameter: 0
      trigger_polarity: 0
      trigger_source: gpio0
      type: ''
      video_mode: format7_mode0
      white_balance_blue: 800
      white_balance_red: 550
    state: []
  pan: 56
  shutter_speed: 0.009995878219604492
  strobe1_delay: 0.0
  strobe1_duration: 1.0
  strobe1_polarity: 1
  tilt: 0
  trigger_delay: 0.0
  trigger_mode: mode0
  trigger_parameter: 0
  trigger_polarity: 0
  trigger_source: gpio0
  video_mode: format7_mode0
  white_balance_blue: 800
  white_balance_red: 550
state: []
