!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  color_backlight_compensation: 1
  color_brightness: 50
  color_contrast: 27
  color_enable_auto_exposure: 1
  color_enable_auto_white_balance: 1
  color_exposure: 156
  color_gain: 33
  color_gamma: 220
  color_hue: 0
  color_saturation: 128
  color_sharpness: 0
  color_white_balance: 6500
  enable_depth: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      color_backlight_compensation: 1
      color_brightness: 13
      color_contrast: 27
      color_enable_auto_exposure: 1
      color_enable_auto_white_balance: 1
      color_exposure: 156
      color_gain: 33
      color_gamma: 220
      color_hue: 0
      color_saturation: 128
      color_sharpness: 0
      color_white_balance: 6500
      enable_depth: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          R200_Depth_Control: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: R200_Depth_Control
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              r200_dc_estimate_median_decrement: 5
              r200_dc_estimate_median_increment: 5
              r200_dc_lr_threshold: 12
              r200_dc_median_threshold: 235
              r200_dc_neighbor_threshold: 90
              r200_dc_preset: 5
              r200_dc_score_maximum_threshold: 420
              r200_dc_score_minimum_threshold: 27
              r200_dc_second_peak_threshold: 70
              r200_dc_texture_count_threshold: 8
              r200_dc_texture_difference_threshold: 80
              state: true
              type: ''
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      r200_auto_exposure_bottom_edge: 479
      r200_auto_exposure_left_edge: 0
      r200_auto_exposure_right_edge: 639
      r200_auto_exposure_top_edge: 0
      r200_emitter_enabled: 1
      r200_lr_auto_exposure_enabled: 0
      r200_lr_exposure: 164
      r200_lr_gain: 400
      state: true
      type: ''
    state: []
  r200_auto_exposure_bottom_edge: 479
  r200_auto_exposure_left_edge: 0
  r200_auto_exposure_right_edge: 639
  r200_auto_exposure_top_edge: 0
  r200_dc_estimate_median_decrement: 5
  r200_dc_estimate_median_increment: 5
  r200_dc_lr_threshold: 12
  r200_dc_median_threshold: 235
  r200_dc_neighbor_threshold: 90
  r200_dc_preset: 5
  r200_dc_score_maximum_threshold: 420
  r200_dc_score_minimum_threshold: 27
  r200_dc_second_peak_threshold: 70
  r200_dc_texture_count_threshold: 8
  r200_dc_texture_difference_threshold: 80
  r200_emitter_enabled: 1
  r200_lr_auto_exposure_enabled: 0
  r200_lr_exposure: 164
  r200_lr_gain: 400
state: []
